# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mybartmod <- function(XMat, sigest, nn, y, n_cov, nu, lambda, nd, burn, numtrees, kfac, pswap, pbd, pb, alpha, beta, nc, minobs, binaryX, dgn) {
    .Call('_GcompBART_mybartmod', PACKAGE = 'GcompBART', XMat, sigest, nn, y, n_cov, nu, lambda, nd, burn, numtrees, kfac, pswap, pbd, pb, alpha, beta, nc, minobs, binaryX, dgn)
}

mybartpred <- function(Gcomp, L1, L2, L3, L4, L5, L6, L7, L8, testXMat, n_cov, testn, nd, burn, numtrees, xi1) {
    .Call('_GcompBART_mybartpred', PACKAGE = 'GcompBART', Gcomp, L1, L2, L3, L4, L5, L6, L7, L8, testXMat, n_cov, testn, nd, burn, numtrees, xi1)
}

mympbartmod <- function(XMat, sigmai1, V1, nu, nn, nndim, y1, n_cov, nd, burn, numtrees, nSigDr, kfac, pswap, pbd, pb, alpha, beta, nc, minobs, binaryX, dgn, Jiao) {
    .Call('_GcompBART_mympbartmod', PACKAGE = 'GcompBART', XMat, sigmai1, V1, nu, nn, nndim, y1, n_cov, nd, burn, numtrees, nSigDr, kfac, pswap, pbd, pb, alpha, beta, nc, minobs, binaryX, dgn, Jiao)
}

mympbartmod1 <- function(XMat, sigmai1, V1, nu, nn, nndim, y1, n_cov, nd, burn, numtrees, nSigDr, kfac, pswap, pbd, pb, alpha, beta, nc, minobs, binaryX, dgn, Jiao) {
    .Call('_GcompBART_mympbartmod1', PACKAGE = 'GcompBART', XMat, sigmai1, V1, nu, nn, nndim, y1, n_cov, nd, burn, numtrees, nSigDr, kfac, pswap, pbd, pb, alpha, beta, nc, minobs, binaryX, dgn, Jiao)
}

mympbartpred <- function(ndim, testn, nd, means, sigmasample, wp, maxy) {
    .Call('_GcompBART_mympbartpred', PACKAGE = 'GcompBART', ndim, testn, nd, means, sigmasample, wp, maxy)
}

mypbartmod <- function(XMat, nn, y, n_cov, nd, burn, numtrees, kfac, pswap, pbd, pb, alpha, beta, nc, minobs, binaryX, dgn) {
    .Call('_GcompBART_mypbartmod', PACKAGE = 'GcompBART', XMat, nn, y, n_cov, nd, burn, numtrees, kfac, pswap, pbd, pb, alpha, beta, nc, minobs, binaryX, dgn)
}

rcpp_hello_world <- function() {
    .Call('_GcompBART_rcpp_hello_world', PACKAGE = 'GcompBART')
}

